### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by ghost** [bheisig/i-doit-docker#3]
### Expected behavior

i-doit search should be working...

### Actual behavior

Search is not working. 

### Steps to reproduce the behavior

Using the latest apache based image ` bheisig/idoit:1.13.2-open-php7.3-apache`:
When typing a search key into the search field and hitting enter, apache answers with a 404 Not found.

### Environment

| Question                  | Answer            |
| ------------------------- | ----------------- |
| i-doit version            | 1.13.2             |
| i-doit edition            | open   |
| PHP version               | 7.3             |
| Service                   | apache |

### Server logs

```
[Wed Nov 13 09:30:41.139297 2019] [core:info] [pid 19] [client 172.17.0.1:37974] AH00128: File does not exist: /var/www/html/search, referer: http://localhost/
172.17.0.1 - - [13/Nov/2019:09:30:41 +0000] "GET /search?q=asdf&rand=1573637441110 HTTP/1.1" 404 271
[Wed Nov 13 09:30:41.279861 2019] [core:info] [pid 19] [client 172.17.0.1:37974] AH00128: File does not exist: /var/www/html/search, referer: http://localhost/
172.17.0.1 - - [13/Nov/2019:09:30:41 +0000] "GET /search?q=asdf HTTP/1.1" 404 271
```

### Steps to FIX the behavior

The apache VHost configuration needs to be adjusted to alllow overrides from the i-doit shipped `.htaccess` file:

```
...
        AllowOverride All
...
```
instead of `None`.

**Comment by bheisig** [comment]
Thanks for your report! And sorry for the late response.

I can confirm the issue you found is a bug. It is fixed in the latest commit, tested and already published to Docker Hub. It would be great if you give it a try and send me feedback. :-)
