### ISSUE TITLE
Missing entry point

### ISSUE THREAD

**Issue by Vierer** [bheisig/i-doit-docker#4]
### Expected behavior

Start of docker image using the example code.

### Actual behavior

Fails with error.

### Steps to reproduce the behavior

# docker run --name i-doit-apache -p 6080:80 bheisig/idoit:1.14-pro-php7.4-apache
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"entrypoint.sh\": executable file not found in $PATH": unknown.
ERRO[0006] error waiting for container: context canceled

I mounted the image and found "entrypoint.sh" without execute rights:
root@c2:~/docker/i-doit# ll /mnt/usr/local/bin/entrypoint.sh
-rw-r--r-- 1 root root 259 Jan 31 23:08 /mnt/usr/local/bin/entrypoint.sh

### Environment

| Question                  | Answer            |
| ------------------------- | ----------------- |
| i-doit version            | 1.14            |
| i-doit edition            | pro and open   |
| PHP version               | 7.4             |
| Service                   | apache  |

**Comment by bheisig** [comment]
Thanks for reporting this issue. Yes, I can confirm that this is a bug. To be more precisely, it _was_ a bug because it was resolved months ago. Sorry that we've taken so long for an answer.
