### ISSUE TITLE
Set AllowOverride to All

### ISSUE THREAD

**Issue by mischkes** [bheisig/i-doit-docker#5]
Hello,

why is AllowOverride in all vhost.conf files set to None? This disables mod_rewrite defined in .htaccess which breaks some parts of the i-doit installation.

Can the setting be changed to "All" in correspondance with non-docker installations? I will gladly provide a patch.

Regards,
Sebastian Mischke

**Comment by bheisig** [comment]
Thanks for reporting this issue! And sorry for the late response. This issue is still open but duplicates issue #3. I close this one.
